spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        prefix: configuration
        defaultContext: apps
        profileSeparator: '::'
      discovery:
        instanceId: my-microservice